# 普通虚拟商品
sku:
  sku_number: '198806140001'
  price: 0.03
  lowest_price: 0.02
  spu_number: 'G198806140'
  term_id: 9


#普通虚拟+实物商品
sku_physical:
  sku_number: '200655000001'
  price: 0.03
  lowest_price: 0
  spu_number: 'G200655000'

# 订金商品
sku_deposit:
  sku_number: '198831000001'
  spu_number: G198831000
