# 普通商品
sku:
  sku_number: '195458000001'
  price: 0.03
  lowest_price: 0.02
  spu_number: 'G195458000'
  term_id: 2

#普通虚拟+实物商品
sku_physical:
  sku_number: '201511000001'
  price: 0.03
  lowest_price: 0
  spu_number: 'G201511000'

# 订金商品
sku_deposit:
  sku_number: '192111000001'
  spu_number: G192111000
