# 普通商品
sku:
  sku_number: '192151000001'
  price: 0.03
  lowest_price: 0.02
  spu_number: 'G192151000'

#普通虚拟+实物商品
sku_physical:
  sku_number: '208802000001'
  price: 0.03
  lowest_price: 0
  spu_number: 'G208802000'
  
# 订金商品
sku_deposit:
  sku_number: '192111000001'
  spu_number: G192111000
