# 普通商品
sku:
  sku_number: '201097030001'
  price: 0.03
  lowest_price: 0.02
  spu_number: 'G201097030'
  term_id: 2
  material_count_1: 6
  material_count_2: 2
  material_number_1: 'SU000001'
  material_number_2: 'SU000004'


#普通虚拟+实物商品
sku_physical:
  sku_number: '202399030001'
  price: 0.03
  lowest_price: 0
  spu_number: 'G202399030'
  
# 订金商品
sku_deposit:
  sku_number: '192111000001'
  spu_number: G192111000
