- config:
    name: 根据属性值ids批量获取属性值信息
    base_url: ${ENV(transaction_admin_api_host)}
    verify: False
    variables:
        - existed_attribute_value_id: 5
        - existed_attribute_value_id2: 31
        - unexist_attribute_value_id: 100000

- test:
    name: 已登录内部账号系统-ids传递长度为1(属性值ID存在)
    request:
        method: GET
        url: /products/attributes/values?ids=$existed_attribute_value_id
        headers:
            Authorization: ${internal_source_user_login_token()}
    validate:
        - eq: [status_code, 200]
        - type_match: [content, list]
        - length_equals: [content.0, 5]

- test:
    name: 已登录内部账号系统-ids传递长度为2(属性值ID都存在)
    request:
        method: GET
        url: /products/attributes/values?ids=$existed_attribute_value_id,$existed_attribute_value_id2
        headers:
            Authorization: ${internal_source_user_login_token()}
    validate:
        - eq: [status_code, 200]
        - type_match: [content, list]
        - length_equals: [content, 2]
        - length_equals: [content.0, 5]

- test:
    name: 已登录内部账号系统-ids传递长度为2(属性值ID一个存在，一个不存在)
    request:
        method: GET
        url: /products/attributes/values?ids=$existed_attribute_value_id,$unexist_attribute_value_id
        headers:
            Authorization: ${internal_source_user_login_token()}
    validate:
        - eq: [status_code, 200]
        - type_match: [content, list]
        - length_equals: [content, 1]
        - length_equals: [content.0, 5]

- test:
    name: 已登录内部账号系统-ids传递长度为1(属性值ID不存在)
    request:
        method: GET
        url: /products/attributes/values?ids=$unexist_attribute_value_id
        headers:
            Authorization: ${internal_source_user_login_token()}
    validate:
        - eq: [status_code, 200]
        - type_match: [content, list]
        - length_equals: [content, 0]

- test:
    name: 已登录内部账号系统-ids传递长度为1(属性值ID为非数字)
    request:
        method: GET
        url: /products/attributes/values?ids=aa
        headers:
            Authorization: ${internal_source_user_login_token()}
    validate:
        - eq: [status_code, 400]


- test:
    name: 未登录内部账号系统-ids传递长度为1(属性值ID存在)
    request:
        method: GET
        url: /products/attributes/values?ids=$existed_attribute_value_id
    validate:
        - eq: [status_code, 401]
        - eq: [content.error_code, '10020005']